#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouryAds
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adsrush")]
	public partial class AdvertisersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_TouryAds_Advertiser(Table_TouryAds_Advertiser instance);
    partial void UpdateTable_TouryAds_Advertiser(Table_TouryAds_Advertiser instance);
    partial void DeleteTable_TouryAds_Advertiser(Table_TouryAds_Advertiser instance);
    partial void InsertTable_TouryAds_Advertisers_Stat(Table_TouryAds_Advertisers_Stat instance);
    partial void UpdateTable_TouryAds_Advertisers_Stat(Table_TouryAds_Advertisers_Stat instance);
    partial void DeleteTable_TouryAds_Advertisers_Stat(Table_TouryAds_Advertisers_Stat instance);
    #endregion
		
		public AdvertisersDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adsrushConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdvertisersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_TouryAds_Advertiser> Table_TouryAds_Advertisers
		{
			get
			{
				return this.GetTable<Table_TouryAds_Advertiser>();
			}
		}
		
		public System.Data.Linq.Table<Table_TouryAds_Advertisers_Stat> Table_TouryAds_Advertisers_Stats
		{
			get
			{
				return this.GetTable<Table_TouryAds_Advertisers_Stat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_TouryAds_Advertisers")]
	public partial class Table_TouryAds_Advertiser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _aid;
		
		private System.Nullable<int> _referaid;
		
		private string _referusername;
		
		private string _email;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _country;
		
		private string _paymentmethod;
		
		private string _skype;
		
		private string _whatsapp;
		
		private System.Nullable<int> _active;
		
		private System.Nullable<int> _suspended;
		
		private System.Nullable<System.DateTime> _signupdate;
		
		private string _signupip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaidChanging(System.Nullable<int> value);
    partial void OnaidChanged();
    partial void OnreferaidChanging(System.Nullable<int> value);
    partial void OnreferaidChanged();
    partial void OnreferusernameChanging(string value);
    partial void OnreferusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnpaymentmethodChanging(string value);
    partial void OnpaymentmethodChanged();
    partial void OnskypeChanging(string value);
    partial void OnskypeChanged();
    partial void OnwhatsappChanging(string value);
    partial void OnwhatsappChanged();
    partial void OnactiveChanging(System.Nullable<int> value);
    partial void OnactiveChanged();
    partial void OnsuspendedChanging(System.Nullable<int> value);
    partial void OnsuspendedChanged();
    partial void OnsignupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignupdateChanged();
    partial void OnsignupipChanging(string value);
    partial void OnsignupipChanged();
    #endregion
		
		public Table_TouryAds_Advertiser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aid", DbType="Int")]
		public System.Nullable<int> aid
		{
			get
			{
				return this._aid;
			}
			set
			{
				if ((this._aid != value))
				{
					this.OnaidChanging(value);
					this.SendPropertyChanging();
					this._aid = value;
					this.SendPropertyChanged("aid");
					this.OnaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referaid", DbType="Int")]
		public System.Nullable<int> referaid
		{
			get
			{
				return this._referaid;
			}
			set
			{
				if ((this._referaid != value))
				{
					this.OnreferaidChanging(value);
					this.SendPropertyChanging();
					this._referaid = value;
					this.SendPropertyChanged("referaid");
					this.OnreferaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referusername", DbType="NVarChar(3500)")]
		public string referusername
		{
			get
			{
				return this._referusername;
			}
			set
			{
				if ((this._referusername != value))
				{
					this.OnreferusernameChanging(value);
					this.SendPropertyChanging();
					this._referusername = value;
					this.SendPropertyChanged("referusername");
					this.OnreferusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(3500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(3500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(3500)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(3500)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(3500)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentmethod", DbType="NVarChar(3500)")]
		public string paymentmethod
		{
			get
			{
				return this._paymentmethod;
			}
			set
			{
				if ((this._paymentmethod != value))
				{
					this.OnpaymentmethodChanging(value);
					this.SendPropertyChanging();
					this._paymentmethod = value;
					this.SendPropertyChanged("paymentmethod");
					this.OnpaymentmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skype", DbType="NVarChar(3500)")]
		public string skype
		{
			get
			{
				return this._skype;
			}
			set
			{
				if ((this._skype != value))
				{
					this.OnskypeChanging(value);
					this.SendPropertyChanging();
					this._skype = value;
					this.SendPropertyChanged("skype");
					this.OnskypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whatsapp", DbType="NVarChar(3500)")]
		public string whatsapp
		{
			get
			{
				return this._whatsapp;
			}
			set
			{
				if ((this._whatsapp != value))
				{
					this.OnwhatsappChanging(value);
					this.SendPropertyChanging();
					this._whatsapp = value;
					this.SendPropertyChanged("whatsapp");
					this.OnwhatsappChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Int")]
		public System.Nullable<int> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suspended", DbType="Int")]
		public System.Nullable<int> suspended
		{
			get
			{
				return this._suspended;
			}
			set
			{
				if ((this._suspended != value))
				{
					this.OnsuspendedChanging(value);
					this.SendPropertyChanging();
					this._suspended = value;
					this.SendPropertyChanged("suspended");
					this.OnsuspendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupdate", DbType="Date")]
		public System.Nullable<System.DateTime> signupdate
		{
			get
			{
				return this._signupdate;
			}
			set
			{
				if ((this._signupdate != value))
				{
					this.OnsignupdateChanging(value);
					this.SendPropertyChanging();
					this._signupdate = value;
					this.SendPropertyChanged("signupdate");
					this.OnsignupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupip", DbType="NVarChar(3500)")]
		public string signupip
		{
			get
			{
				return this._signupip;
			}
			set
			{
				if ((this._signupip != value))
				{
					this.OnsignupipChanging(value);
					this.SendPropertyChanging();
					this._signupip = value;
					this.SendPropertyChanged("signupip");
					this.OnsignupipChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_TouryAds_Advertisers_Stats")]
	public partial class Table_TouryAds_Advertisers_Stat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _username;
		
		private System.Nullable<int> _month;
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _imp;
		
		private System.Nullable<int> _clicks;
		
		private System.Nullable<float> _bid;
		
		private System.Nullable<float> _spending;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnmonthChanging(System.Nullable<int> value);
    partial void OnmonthChanged();
    partial void OnyearChanging(System.Nullable<int> value);
    partial void OnyearChanged();
    partial void OnimpChanging(System.Nullable<int> value);
    partial void OnimpChanged();
    partial void OnclicksChanging(System.Nullable<int> value);
    partial void OnclicksChanged();
    partial void OnbidChanging(System.Nullable<float> value);
    partial void OnbidChanged();
    partial void OnspendingChanging(System.Nullable<float> value);
    partial void OnspendingChanged();
    #endregion
		
		public Table_TouryAds_Advertisers_Stat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(500)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_month", DbType="Int")]
		public System.Nullable<int> month
		{
			get
			{
				return this._month;
			}
			set
			{
				if ((this._month != value))
				{
					this.OnmonthChanging(value);
					this.SendPropertyChanging();
					this._month = value;
					this.SendPropertyChanged("month");
					this.OnmonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this.OnyearChanging(value);
					this.SendPropertyChanging();
					this._year = value;
					this.SendPropertyChanged("year");
					this.OnyearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imp", DbType="Int")]
		public System.Nullable<int> imp
		{
			get
			{
				return this._imp;
			}
			set
			{
				if ((this._imp != value))
				{
					this.OnimpChanging(value);
					this.SendPropertyChanging();
					this._imp = value;
					this.SendPropertyChanged("imp");
					this.OnimpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clicks", DbType="Int")]
		public System.Nullable<int> clicks
		{
			get
			{
				return this._clicks;
			}
			set
			{
				if ((this._clicks != value))
				{
					this.OnclicksChanging(value);
					this.SendPropertyChanging();
					this._clicks = value;
					this.SendPropertyChanged("clicks");
					this.OnclicksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid", DbType="Real")]
		public System.Nullable<float> bid
		{
			get
			{
				return this._bid;
			}
			set
			{
				if ((this._bid != value))
				{
					this.OnbidChanging(value);
					this.SendPropertyChanging();
					this._bid = value;
					this.SendPropertyChanged("bid");
					this.OnbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spending", DbType="Real")]
		public System.Nullable<float> spending
		{
			get
			{
				return this._spending;
			}
			set
			{
				if ((this._spending != value))
				{
					this.OnspendingChanging(value);
					this.SendPropertyChanging();
					this._spending = value;
					this.SendPropertyChanged("spending");
					this.OnspendingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
